version: '3.9'

networks:
  lpmNetwork:
    driver: bridge

services:
  lpm_web:
    container_name: lpm_web
    build:
        context: ../LPM.WebApp
        dockerfile: Dockerfile
    networks:
        - lpmNetwork
  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
        - "7000"
    ports:
        - "7000:7000"
    networks:
        - lpmNetwork
    volumes:
        - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
        - lpm_api
  lpm_api:
    container_name: lpm_api
    build:
        context: ../
        dockerfile: Dockerfile
    volumes:
        - ./cons:/usr/src/app
    ports:
        - "8080:8080"
    networks:
        - lpmNetwork
    depends_on:
        - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "LPM_BD"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
        - lpmNetwork
    volumes:
        - lpm-data:/var/lib/postgresql/data

volumes:
    lpm-data: